### ISSUE TITLE
python3path.txt (No such file or directory)

### ISSUE THREAD

**Issue by Kommandocentralen** [jnowak90/CytoSeg2.0#3]
I get the following error after typing in the location of python3:

> java.io FileNotFoundException: ~/.../Fiji.app/plugins/CytoSeg/python3path.txt (No such file or directory) in line 318 (called from line 353)
> 
> File . saveString (pathToPython3 , pathToPythonPathFile <)>:

I am running Linux Mint. I have typed in the location provided by the statement "which python3":

> /usr/bin/python3

Could the problem be that my python3 is not located in the home folder i.e. a permission issue? I have tried to run Fiji through the terminal with the sudo command but it does not help.

Any suggestions?

**Comment by gnies** [comment]
I do not know what went wrong but maybe you could try adding the file Fiji.app/plugins/CytoSeg/python3path.txt  manually and see what happens. 
The text file should just contain the following in the first line: /usr/bin/python3

**Comment by Kommandocentralen** [comment]
Thanks for the reply. I figured out what was wrong - I didn't rename the folder to "CytoSeg" as instructed.
